"""add-timestamps

Revision ID: 6ddedb19080c
Revises: b9c2ea77e8ee
Create Date: 2017-11-01 11:24:01.151534

"""
import datetime

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '6ddedb19080c'
down_revision = 'b9c2ea77e8ee'
branch_labels = ()
depends_on = None


def upgrade():
    current_time = str(datetime.datetime.utcnow())
    op.add_column(
        'landings',
        sa.Column(
            'created',
            sa.DateTime(),
            nullable=False,
            server_default=current_time
        )
    )
    op.add_column(
        'landings',
        sa.Column(
            'updated',
            sa.DateTime(),
            nullable=False,
            server_default=current_time
        )
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('landings', 'updated')
    op.drop_column('landings', 'created')
    # ### end Alembic commands ###
