"""add duration_seconds to landing_job

Revision ID: a406ce1331f9
Revises: c9b121e82708
Create Date: 2020-12-01 20:20:04.969768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a406ce1331f9"
down_revision = "c9b121e82708"
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "landing_job", sa.Column("duration_seconds", sa.Integer(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("landing_job", "duration_seconds")
    # ### end Alembic commands ###
