"""store_active_diff_id

Revision ID: b9c2ea77e8ee
Revises: 5d2d28b723b3
Create Date: 2017-09-20 11:59:32.318423

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'b9c2ea77e8ee'
down_revision = '5d2d28b723b3'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'landings', sa.Column('active_diff_id', sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('landings', 'active_diff_id')
    # ### end Alembic commands ###
