"""adds formatted_replacements field

Revision ID: ffc1d1b8652a
Revises: 772c77c15667
Create Date: 2021-04-09 01:09:48.109637

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "ffc1d1b8652a"
down_revision = "772c77c15667"
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "landing_job",
        sa.Column(
            "formatted_replacements",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("landing_job", "formatted_replacements")
    # ### end Alembic commands ###
