# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

FROM python:3.5-alpine

RUN apk --update --no-cache add \
	sqlite
RUN mkdir /db

COPY requirements.txt dev-requirements.txt /

RUN set -ex \
    && apk add --no-cache --virtual .build-deps \
           gcc \
           libc-dev \
           musl-dev \
           linux-headers \
           pcre-dev \
    && pip install --no-cache -r /requirements.txt \
    && pip install --no-cache -r /dev-requirements.txt \
	&& runDeps="$( \
		scanelf --needed --nobanner --recursive /usr/local \
			| awk '{ gsub(/,/, "\nso:", $2); print "so:" $2 }' \
			| sort -u \
			| xargs -r apk info --installed \
			| sort -u \
	)" \
	&& apk add --virtual .python-rundeps $runDeps \
    && apk del .build-deps

# Create a Dockerflow version file at the root so
# we don't map over it below.
RUN echo '{\
    "source": "https://github.com/mozilla-conduit/lando-api",\
    "version": "0.0.0",\
    "commit": "",\
    "build": "dev"\
}' >> /version.json

ADD . /app
WORKDIR /app

# We install outside of the app directory to create the .egg-info in a
# location that will not be mounted over. This means /app needs to be
# added to PYTHONPATH though.
ENV PYTHONPATH /app
RUN cd / && pip install --no-cache /app
CMD ["lando-api-dev"]
