"""Set Phab-related Revision fields to nullable and add target field.

Revision ID: 06cc1c6a04b5
Revises: 50ffadceca83
Create Date: 2023-06-12 20:12:46.910910

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "06cc1c6a04b5"
down_revision = "50ffadceca83"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "landing_job", sa.Column("target_commit_hash", sa.Text(), nullable=True)
    )
    op.alter_column(
        "revision", "revision_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column("revision", "diff_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("revision", "diff_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column(
        "revision", "revision_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.drop_column("landing_job", "target_commit_hash")
    # ### end Alembic commands ###
