"""add revision data

Revision ID: 2610406c9364
Revises: 50ffadceca83
Create Date: 2023-06-06 15:29:45.635067

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "2610406c9364"
down_revision = "50ffadceca83"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "revision",
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("revision", "data")
    # ### end Alembic commands ###
