"""add revision data

Revision ID: 30f138015afc
Revises: 06cc1c6a04b5
Create Date: 2023-08-29 19:56:50.013421

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "30f138015afc"
down_revision = "06cc1c6a04b5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "revision",
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("revision", "data")
    # ### end Alembic commands ###
