"""rename fields

Revision ID: 4d0f0fac29f4
Revises: 9083afb011cd
Create Date: 2022-09-15 18:30:01.904315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4d0f0fac29f4"
down_revision = "9083afb011cd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("revision", sa.Column("predecessor_id", sa.Integer(), nullable=True))
    op.drop_constraint("revision_depends_on_id_fkey", "revision", type_="foreignkey")
    op.create_foreign_key(None, "revision", "revision", ["predecessor_id"], ["id"])
    op.drop_column("revision", "depends_on_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "revision",
        sa.Column("depends_on_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "revision", type_="foreignkey")
    op.create_foreign_key(
        "revision_depends_on_id_fkey", "revision", "revision", ["depends_on_id"], ["id"]
    )
    op.drop_column("revision", "predecessor_id")
    # ### end Alembic commands ###
