"""add base commit vcs format

Revision ID: 50431b1b2fc6
Revises: 1dfc5aa9d1b2
Create Date: 2025-04-24 17:45:12.173306

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "50431b1b2fc6"
down_revision = "1dfc5aa9d1b2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "landing_job", sa.Column("target_commit_hash_vcs", sa.Text(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("landing_job", "target_commit_hash_vcs")
    # ### end Alembic commands ###
