"""add revision_landing_job.diff_id

Revision ID: 50ffadceca83
Revises: a8cd4d43c4c3
Create Date: 2023-05-25 01:50:36.755884

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "50ffadceca83"
down_revision = "a8cd4d43c4c3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "revision_landing_job", sa.Column("diff_id", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("revision_landing_job", "diff_id")
    # ### end Alembic commands ###
