"""Set Phab-related Revision fields to nullable.

Revision ID: 85f90f58bb7f
Revises: 50ffadceca83
Create Date: 2023-06-09 15:47:01.812520

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "85f90f58bb7f"
down_revision = "50ffadceca83"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("landing_job", sa.Column("target_cset", sa.Text(), nullable=True))
    op.alter_column(
        "revision", "revision_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column("revision", "diff_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("revision", "diff_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column(
        "revision", "revision_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.drop_column("landing_job", "target_cset")
    # ### end Alembic commands ###
