"""revision landing jobs

Revision ID: a8cd4d43c4c3
Revises: c5b4350e073b
Create Date: 2023-05-01 16:03:39.129725

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "a8cd4d43c4c3"
down_revision = "c5b4350e073b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "revision_landing_job",
        sa.Column("landing_job_id", sa.Integer(), nullable=True),
        sa.Column("revision_id", sa.Integer(), nullable=True),
        sa.Column("index", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["landing_job_id"],
            ["landing_job.id"],
        ),
        sa.ForeignKeyConstraint(
            ["revision_id"],
            ["revision.id"],
        ),
    )
    op.alter_column(
        "landing_job",
        "status",
        existing_type=postgresql.ENUM(
            "SUBMITTED",
            "IN_PROGRESS",
            "DEFERRED",
            "FAILED",
            "LANDED",
            "CANCELLED",
            name="landingjobstatus",
        ),
        nullable=True,
    )
    op.alter_column(
        "landing_job",
        "revision_to_diff_id",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
    )
    op.alter_column(
        "landing_job",
        "revision_order",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "landing_job",
        "revision_order",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
    )
    op.alter_column(
        "landing_job",
        "revision_to_diff_id",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
    )
    op.alter_column(
        "landing_job",
        "status",
        existing_type=postgresql.ENUM(
            "SUBMITTED",
            "IN_PROGRESS",
            "DEFERRED",
            "FAILED",
            "LANDED",
            "CANCELLED",
            name="landingjobstatus",
        ),
        nullable=False,
    )
    op.drop_table("revision_landing_job")
    # ### end Alembic commands ###
