"""add Treestatus models

Revision ID: ddd71b4a0545
Revises: 7883d80258fb
Create Date: 2023-03-11 02:26:57.117613

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ddd71b4a0545"
down_revision = "7883d80258fb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("tree", sa.String(length=32), nullable=False),
        sa.Column("when", sa.DateTime(timezone=True), nullable=False),
        sa.Column("who", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=64), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("tags", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_log_tree"), "log", ["tree"], unique=False)
    op.create_index(op.f("ix_log_when"), "log", ["when"], unique=False)
    op.create_table(
        "status_change",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("who", sa.Text(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("when", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_status_change_when"), "status_change", ["when"], unique=False
    )
    op.create_table(
        "tree",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("tree", sa.String(length=32), nullable=True),
        sa.Column("status", sa.String(length=64), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("message_of_the_day", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tree_tree"), "tree", ["tree"], unique=True)
    op.create_table(
        "status_change_tree",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("stack_id", sa.Integer(), nullable=True),
        sa.Column("tree", sa.String(length=32), nullable=False),
        sa.Column("last_state", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["stack_id"],
            ["status_change.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_status_change_tree_stack_id"),
        "status_change_tree",
        ["stack_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_status_change_tree_tree"), "status_change_tree", ["tree"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_status_change_tree_tree"), table_name="status_change_tree")
    op.drop_index(
        op.f("ix_status_change_tree_stack_id"), table_name="status_change_tree"
    )
    op.drop_table("status_change_tree")
    op.drop_index(op.f("ix_tree_tree"), table_name="tree")
    op.drop_table("tree")
    op.drop_index(op.f("ix_status_change_when"), table_name="status_change")
    op.drop_table("status_change")
    op.drop_index(op.f("ix_log_when"), table_name="log")
    op.drop_index(op.f("ix_log_tree"), table_name="log")
    op.drop_table("log")
    # ### end Alembic commands ###
